apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-mkdocs-container-image-xtq98v
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations: {}
        generateName: mkdocs-container-image-
        labels:
          tekton.dev/pipeline: mkdocs-container-image
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-rev
            value: $(tt.params.git-revision)
        pipelineRef:
          name: mkdocs-container-image
        resources: []
        status: null
        workspaces: []
