apiVersion: tekton.dev/v1beta1
kind: Task
  name: mkdocs-lint
spec:
  params:
    - description: The docs github repository
      name: gitUrl
      type: string
    - description: The git revision to checkout
      name: gitRevision
      type: string
  steps:
    - image: 'manojjahgirdar/mkdocs-builder:v1.12'
      name: mkdocs-spell-lint
      resources: {}
      script: |
        #!/usr/bin/env sh

        echo "------Cloning mkdocs repo------"
        git clone "$(params.gitUrl)" ./mkdocs || exit 1
        echo "-------------------------------"

        echo "-------Linting spellings-------"
        node lint/node_modules/cspell/bin.js mkdocs/**/*.md || exit 1
        echo "-------------------------------"
